language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - travis # To debug .travis.yml

addons:
  apt:
    sources:
      # Boost 1.58
      - sourceline: ppa:kzemek/boost
    packages:
      - libboost1.58-dev
      - openmpi-bin
      - openmpi-common
      - openmpi-doc
      - libopenmpi-dev
      - libhdf5-serial-dev

install: true

env:
  - ENABLE_MPI=ON ALPS_CC=mpicc ALPS_CXX=mpic++

before_script:
  - export OMPI_CC=${CC}
  - export OMPI_CXX=${CXX}

script:
  # Stop on first error
  - set -e

  # Create directory for installed prerequisites
  - export PREREQS_DIR=$(readlink -f $TRAVIS_BUILD_DIR/../installed)
  - mkdir $PREREQS_DIR

  # Install ALPSCore wo tests
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/ALPSCore/ALPSCore.git ALPSCore.git
  - mkdir ALPSCore.build && pushd ALPSCore.build
  - |
    cmake ../ALPSCore.git                                 \
    -DCMAKE_C_COMPILER=${ALPS_CC:-${CC}}                  \
    -DCMAKE_CXX_COMPILER=${ALPS_CXX:-${CXX}}              \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR/ALPSCore          \
    -DALPS_INSTALL_EIGEN=true                             \
    -DTesting=false                                       \
    -DENABLE_MPI=$ENABLE_MPI
  - make -j3
  - make install
  - export ALPSCore_DIR=$PREREQS_DIR/ALPSCore
   
  # Build, test and install ALPSCore/CT-HYB
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build
  - cd build
  - |
    cmake ../CT-HYB                                       \
    -DCMAKE_BUILD_TYPE=Debug                              \
    -DCMAKE_C_COMPILER=${ALPS_CC:-${CC}}                  \
    -DCMAKE_CXX_COMPILER=${ALPS_CXX:-${CXX}}              \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed
  - make -j3
  - make test
  - make install
